<?php 

$leftContent = '';

$rightContent = '';

$dirPublic = APPLICATIONBASEDIR;

$baseUrl = $this->baseUrl();

$cssFiles = array
(
    '/public/css/bootstrap.min.css',
    '/public/css/style.css',
);

$jsFiles = array
(
    'https://code.jquery.com/jquery-1.10.2.min.js',
    //'/public/js/script.js',
);

foreach ($cssFiles as $key => $cssFile)
{
    $filepath = $dirPublic . $cssFile;
    
    if (stripos($cssFile, 'http') !== 0 && file_exists($filepath) && is_readable($filepath))
    {
        $filetime = filemtime($filepath);
        
        $cssFiles[$key] = $baseUrl . $cssFile . '?filetime=' . $filetime;
    }
    elseif (stripos($cssFile, 'http') !== 0)
    {
        unset($cssFiles[$key]);
    }
}

foreach ($jsFiles as $key => $jsFile)
{
    $filepath = $dirPublic . $jsFile;
    
    if (stripos($jsFile, 'http') !== 0 && file_exists($filepath) && is_readable($filepath))
    {
        $filetime = filemtime($filepath);
        
        $jsFiles[$key] = $baseUrl . $jsFile . '?filetime=' . $filetime;
    }
    elseif (stripos($jsFile, 'http') !== 0)
    {
        unset($jsFiles[$key]);
    }
}
?>
<html <?php echo 'xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"';?>>
<head>
<?php 
foreach ($cssFiles as $cssFile)
{
?>
    <link href="<?php echo $cssFile;?>" media="all" rel="stylesheet" type="text/css">
<?php 
}
?>
<?php #echo $headTitle; ?>
<?php #echo $headMeta; ?>
<?php #echo $headLink; ?>
<?php #echo $headScript; ?>
<?php #echo $headStyle; ?>
</head>
<body>
    <div class="container">
        <br /><br /><br />  
                        <?php 
                            echo $this->maincontent;
                        ?>
        <br /><br /><br /><br />
    </div>
<?php 
foreach ($jsFiles as $jsFile)
{
?>
    <script type="text/javascript" src="<?php echo $jsFile;?>"></script>
<?php 
}
?>
</body>
</html>
