<?php 
$invokeParams = $this->invokeParams;
?>
 <form id="coupon_capture" method="post">
<div class="row">
    <div class="col-sm-6" style="border-right: 1px solid #ADADAD;">

<!-- ### Neue Felder ### -->

        <input class=" col-sm-12 semiBold" name="idext" type="text" value="<?php echo $this->escape($invokeParams['idext']);?>" placeholder="ID_EXT" disabled="disabled" /><br /><br />

<!-- ### Ende Neue Felder ### -->      
            
           
<?php 
if (isset($this->error['salutation']))
{
    foreach($this->error['salutation'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
            <div class=" col-sm-12 noPadding">
                <select class="col-sm-12" name="salutation">
                    <option value="Herr" <?php echo (isset($invokeParams['salutation']) && $invokeParams['salutation'] == 'Herr') ? 'selected="selected"' : '';?>>Herr</option>
                    <option value="Frau" <?php echo (isset($invokeParams['salutation']) && $invokeParams['salutation'] == 'Frau') ? 'selected="selected"' : '';?>>Frau</option>
                </select>
            </div><br /><br />
<?php 
if (isset($this->error['firstname']))
{
    foreach($this->error['firstname'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
            <input class=" col-sm-12 semiBold" name="firstname" type="text" placeholder="Vorname" value="<?php echo $this->escape($invokeParams['firstname']);?>"/><br /><br />
<?php 
if (isset($this->error['secondname']))
{
    foreach($this->error['secondname'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
            <input class=" col-sm-12 semiBold" name="secondname" type="text" placeholder="Nachname" value="<?php echo $this->escape($invokeParams['secondname']);?>"/><br /><br />

  
<!-- ### Neue Felder ### -->

<?php 
if (isset($this->error['street']))
{
    foreach($this->error['street'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
<input class=" col-sm-12 semiBold" name="street" type="text" placeholder="Straße" value="<?php echo $this->escape($invokeParams['street']);?>"/><br /><br />
<?php 
if (isset($this->error['postcode']))
{
    foreach($this->error['postcode'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
<input class=" col-sm-12 semiBold" name="postcode" type="text" placeholder="Postleitzahl" value="<?php echo $this->escape($invokeParams['postcode']);?>"/><br /><br />
<?php 
if (isset($this->error['city']))
{
    foreach($this->error['city'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
<input class=" col-sm-12 semiBold" name="city" type="text" placeholder="Ort" value="<?php echo $this->escape($invokeParams['city']);?>"/><br /><br />
<?php 
if (isset($this->error['birthday']))
{
    foreach($this->error['birthday'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
<input class=" col-sm-12 semiBold" name="birthday" type="text" placeholder="Geburtsdatum" value="<?php echo $this->escape($invokeParams['birthday']);?>"/><br /><br />
<?php 
if (isset($this->error['date_vk']))
{
    foreach($this->error['date_vk'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
<input class=" col-sm-12 semiBold" name="date_vk" type="text" placeholder="Datum VK" disabled="disabled" value="<?php echo $this->escape($invokeParams['date_vk']);?>"/><br /><br />

<!-- ### Ende Neue Felder ### -->  
    </div>
    <div class="col-sm-6">
       
<!-- ### Neue Felder ### -->            

<?php 
if (isset($this->error['adress_source']))
{
    foreach($this->error['adress_source'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
<input class=" col-sm-12 semiBold" name="adress_source" type="text" placeholder="Adressherkunft" disabled="disabled" value="<?php echo $this->escape($invokeParams['adress_source']);?>"/><br /><br />
<?php 
if (isset($this->error['decline_reason']))
{
    foreach($this->error['decline_reason'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
<input class=" col-sm-12 semiBold" name="decline_reason" type="text" placeholder="Ablehnungsgrund" disabled="disabled" value="<?php echo $this->escape($invokeParams['decline_reason']);?>"/><br /><br />
<?php 
if (isset($this->error['pre_phone_selection']))
{
    foreach($this->error['pre_phone_selection'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
<input class=" col-sm-12 semiBold" name="pre_phone_selection" type="text" placeholder="Vorwahl" value="<?php echo $this->escape($invokeParams['pre_phone_selection']);?>"/><br /><br />
            
<!-- ### Ende Neue Felder ### -->        
   
<?php 
if (isset($this->error['phonenumber']))
{
    foreach($this->error['phonenumber'] as $errorMessage)
    {
?>
            <p class=" col-sm-12 semiBold" style="color:#ff0000;"><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>  
         
            <input class=" col-sm-12 semiBold" name="phonenumber" type="text" placeholder="Telefonnummer" value="<?php echo $this->escape($invokeParams['phonenumber']);?>"/><br /><br />
                    
<?php 
if (isset($this->error['email']))
{
    foreach($this->error['email'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>              
                         
   <input class=" col-sm-12 semiBold" name="email" type="text" placeholder="E-Mail-Adresse" value="<?php echo $this->escape($invokeParams['email']);?>"/><br /><br />

   
   
<!-- ### Neue Felder ### -->            

<?php 
if (isset($this->error['comment']))
{
    foreach($this->error['comment'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
<input class=" col-sm-12 semiBold" name="comment" type="text" placeholder="Bemerkung" value="<?php echo $this->escape($invokeParams['comment']);?>"/><br /><br />
            
<!-- ### Ende Neue Felder ### -->   
   
   
<?php 
if (isset($this->error['received']))
{
    foreach($this->error['received'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>       
   
    <input class=" col-sm-12 semiBold" name="received" type="text" placeholder="Erhalten am im Format JJJJ-MM-TT" value="<?php echo $this->escape($invokeParams['received']);?>"/><br /><br />
  
<?php 
if (isset($this->error['called']))
{
    foreach($this->error['called'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>    
    
     <input class=" col-sm-12 semiBold" name="called" type="text" placeholder="Angerufen am im Format JJJJ-MM-TT" value="<?php echo $this->escape($invokeParams['called']);?>"/><br /><br />

 <?php 
if (isset($this->error['agent']))
{
    foreach($this->error['agent'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>               
                
    <input class=" col-sm-12 semiBold" name="agent" type="text" placeholder="Agent" value="<?php echo $this->escape($invokeParams['agent']);?>"/><br /><br />
            
            
<?php /*?>
            <br /><br />
            <div class=" col-sm-11 greenColor semiBold center"><br /><div id="message"></div></div>
            <div id="coupon_capture_submit" class=" col-sm-12 pointer button">Datensatz speichern</div>
<?php */?>
        
    </div>
    
</div>
<br />
<div class="row">
    <div class="col-sm-offset-3 col-sm-6">      
<?php 
if (isset($this->error['warrant']))
{
    foreach($this->error['warrant'] as $errorMessage)
    {
?>
            <p><?php echo  $this->escape($errorMessage);?></p><br /><br />
<?php 
    }
}
?>
        <input style="transform: scale(2); float: left;" name="warrant" type="checkbox" value="send warrant" <?php if (!empty($invokeParams['agent'])){echo 'checked="checked"';}?> /><div style="font-size: 20px; margin-left: 15px; float: left;">Möchte Vollmacht haben</div>
    </div>
</div>
<div class="row">
    <div class="col-sm-offset-3 col-sm-6">
        <div class=" col-sm-11 greenColor semiBold center"><br /><div id="message"></div></div>
            <input id="coupon_capture_submit" class=" col-sm-12 pointer button" name="submit" type="submit" value="Datensatz speichern"/>
    </div>
</div>
</form>  