<?php 
$invokeParams = $this->invokeParams;
?>
 <form id="search_data" method="post">
<div class="row">
   
    <div class="col-sm-offset-3 col-sm-5">
       
          

<input class=" col-sm-12 semiBold" name="search_name" type="text" placeholder="Name" disabled="disabled" value=""/><br /><br />
            
     
   
<div class="row">
    <div class="col-sm-offset-3 col-sm-5">
        <div class=" col-sm-11 greenColor semiBold center"><br /><div id="message"></div></div>
            <input id="search_submit" class=" col-sm-12 pointer button" name="searcg_submit" type="submit" value="Datensatz suchen"/>
    </div>
</div>
</form>  