<?php 
$invokeParams = $this->invokeParams;
?>
<form id="search_data" method="post">
<div class="row">
    <div class="col-sm-offset-3 col-sm-6">   
<input class=" col-sm-12 semiBold" name="search_name" type="text" placeholder="Name" value="<?php echo $this->escape($invokeParams['search_name']);?>"/>
    </div>
</div><br /><br />
<div class="row">
    <div class="col-sm-offset-3 col-sm-5">
        <div class=" col-sm-11 greenColor semiBold center"><br /><div id="message"></div></div>
            <input id="search_submit" class=" col-sm-12 pointer button" name="searcg_submit" type="submit" value="Datensatz suchen"/>
    </div>
</div>
</form>  

<div class="row">
    <div class="col-sm-12">
<?php
foreach ($this->userProfiles as $userProfile)
{
?>
        <div>
            <p><a href="<?php echo $this->url(array('id'=>$userProfile['user_profile_id']), 'frontend-main-intranet-view', true);?>"><?php echo $this->escape($userProfile['firstname'] . ' ' . $userProfile['secondname'] . ', ' . $userProfile['city']);?></a></p>
        </div>
<?php
}
?>
    </div>
</div>